---
- hosts: all

  tasks:
  - name: Create directory nginxproxymanager
    ansible.builtin.file:
      path: /root/nginxproxymanager/
      state: directory
      owner: root
      group: root
      mode: '0644'

  - name: copy Docker Compose files
    copy:
      src: ../docker/vps01/nginxproxymanager/{{ item }}
      dest: /root/nginxproxymanager/{{ item }}
    loop:
    - docker-compose.yml

  # use files parameter to use multiple docker-compose.yml files
  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /root/nginxproxymanager
      pull: yes
      recreate: always
      files:
      - docker-compose.yml